
// Code generated by hero.
// source: C:\Users\hduoct\Desktop\GoWeb\Menu\body.html
// DO NOT EDIT!
package UserIndex
import (
	"github.com/shiyanhui/hero"
	"io"
	"../../Entity"
	"github.com/kataras/iris"
	"strconv"
)
func UserIndexWriter(ctx iris.Context,w io.Writer,entity Entity.Entity) (int, error){
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>index</title>
    <!-- Bootstrap -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <style type="text/css">
        body{ font-family: Microsoft YaHei,'宋体' , Tahoma, Helvetica, Arial, "\5b8b\4f53", sans-serif;}
    </style>
    <script src="https://cdn.bootcss.com/markdown.js/0.6.0-beta1/markdown.min.js"></script>
</head>
<body>
`)
	_buffer.WriteString(`
<nav id="navbar-example" class="navbar navbar-default navbar-static" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse"
                    data-target=".bs-js-navbar-scrollspy">
                <span class="sr-only">切换导航</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Web开发学习笔记</a>
        </div>
        <div class="collapse navbar-collapse bs-js-navbar-scrollspy">
            <ul class="nav navbar-nav">`)
	for i,m := range entity.MenuList {
		_buffer.WriteString(`<li><a href="/menu/`+strconv.Itoa(i+1)+`/1">`+m.Name+`</a></li>`)
	}
	_buffer.WriteString(`
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search" value="golang是最好的语言">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
				<li><a href="/adminlogin">后台</a></li>`)
	if auth, _ := Entity.Sess.Start(ctx).GetBoolean("userauthenticated"); !auth {
		_buffer.WriteString(`<li><a href="/register">注册</a></li>`+`<li><a href="/login">登录</a></li>`)
	}else {
		_buffer.WriteString(`<li><a href="/user">欢迎你&nbsp;:&nbsp;`+Entity.Sess.Start(ctx).GetString("Username")+`&nbsp;&nbsp;&nbsp;更多</a></li>`)
	}
	_buffer.WriteString(`
            </ul>
        </div>
    </div>
</nav>
`)
//<div style="margin-top:15%;margin-left:20%;margin-right:20%">
	//<button  class="btn btn-default" name="btn" id="btn" onclick="javascript:window.location.href='/chatform';">聊天室</button>
// </div>
	_buffer.WriteString(`
<div class="row">
	<div class="col-md-2 col-lg-2 hidden-sm hidden-xs"></div>
	<div class="col-md-8 col-lg-8 col-sm-12 col-xs-12">
		<ul class="nav nav-pills">
	  		<li role="presentation" class="active"><a href="#">主页</a></li>
	  		<li role="presentation"><a href="/chatform">聊天室</a></li>
	  		<li role="presentation"><a href="#">上传照片</a></li>
			<li role="presentation"><a href="#">修改信息</a></li>
</ul>
	</div>
	<div class="col-md-2 col-lg-2 hidden-sm hidden-xs"></div>
</div>
</body>
</html>`)
	return w.Write(_buffer.Bytes())

}